import { AuditReport, AuditIssue, CategoryKey, Severity } from "@/types/audit";

const demoIssues: AuditIssue[] = [
  // CRITICAL (3)
  {
    id: 1,
    title: "Sin schema markup de Physician/MedicalBusiness",
    category: "llm",
    severity: "critical",
    description: "No se encontró markup de schema `Physician`, `MedicalBusiness` o `LocalBusiness` en ninguna página.",
    whyItMatters: "Los sistemas de IA como ChatGPT y Gemini no pueden verificar credenciales, certificaciones o formación sin datos estructurados. Cuando los pacientes piden recomendaciones, los competidores con schema adecuado son citados primero.",
  },
  {
    id: 2,
    title: "Sin schema FAQPage",
    category: "llm",
    severity: "critical",
    description: "No se encontró schema `FAQPage` en la sección de preguntas frecuentes a pesar de tener contenido de FAQ.",
    whyItMatters: "Los asistentes de IA no citarán tus respuestas FAQ para preguntas comunes porque no pueden identificar el contenido como datos FAQ estructuralmente.",
  },
  {
    id: 3,
    title: "Título de página principal demasiado largo",
    category: "seo",
    severity: "critical",
    description: "El título de la página principal tiene 120 caracteres, más del doble de la longitud recomendada de 50-60 caracteres.",
    whyItMatters: "Google trunca los títulos más allá de aproximadamente 60 caracteres en los resultados de búsqueda. El nombre de tu negocio y diferenciadores clave se cortan, reduciendo la tasa de clics.",
  },

  // MAJOR (18)
  {
    id: 4,
    title: "Artículos de blog sin autor médico",
    category: "seo",
    severity: "major",
    description: "Los artículos del blog están publicados por una cuenta genérica en lugar de un profesional médico con nombre.",
    whyItMatters: "Las directrices E-E-A-T de Google enfatizan la experiencia del autor para contenido médico. Los artículos de una cuenta genérica no tienen autoridad médica frente a competidores con autores profesionales.",
  },
  {
    id: 5,
    title: "URLs con errores ortográficos",
    category: "seo",
    severity: "major",
    description: "Se encontraron categorías de URL con errores ortográficos en procedimientos clave.",
    whyItMatters: "Las URLs mal escritas no rankean para las palabras clave correctas y desperdician link equity interno en términos de búsqueda inexistentes.",
  },
  {
    id: 6,
    title: "Categoría de plantilla expuesta",
    category: "seo",
    severity: "major",
    description: "Existe una categoría de plantilla interna visible en el sitemap como artefacto de desarrollo.",
    whyItMatters: "Una plantilla indexada indica al buscador que el sitio tiene contenido sin terminar, minando la credibilidad profesional.",
  },
  {
    id: 7,
    title: "Open Graph title genérico",
    category: "seo",
    severity: "major",
    description: "El `og:title` de la página principal es simplemente 'Home' en lugar de un título descriptivo con nombre del negocio y ubicación.",
    whyItMatters: "Cuando la página se comparte en redes sociales, 'Home' aparece en lugar de branding profesional, haciendo que los shares parezcan enlaces rotos.",
  },
  {
    id: 8,
    title: "Imagen Open Graph débil",
    category: "seo",
    severity: "major",
    description: "La `og:image` es un ícono pequeño de 512x512 en lugar de una imagen profesional de alta resolución.",
    whyItMatters: "Las plataformas sociales muestran imágenes de vista previa prominentemente. Un ícono recortado pequeño se ve poco profesional.",
  },
  {
    id: 9,
    title: "Sin schema de Reviews",
    category: "llm",
    severity: "major",
    description: "No se encontró schema `Review` o `AggregateRating` en la página de testimonios a pesar de tener reseñas de pacientes.",
    whyItMatters: "Los asistentes de IA usan datos estructurados de reseñas para evaluar reputación. Sin schema, tus testimonios son invisibles para algoritmos de confianza.",
  },
  {
    id: 10,
    title: "Schema de artículos sin atribución médica",
    category: "llm",
    severity: "major",
    description: "El schema `Article` de los posts atribuye autoría a la marca en lugar de un profesional médico.",
    whyItMatters: "Los sistemas de IA rastrean la autoría para determinar experiencia médica. Artículos por una marca tienen cero autoridad médica.",
  },
  {
    id: 11,
    title: "Sin archivo llms.txt",
    category: "llm",
    severity: "major",
    description: "No se detectó archivo `llms.txt` en la raíz del sitio (devuelve 404).",
    whyItMatters: "Este protocolo emergente indica a los crawlers de IA el propósito de tu sitio. Los early adopters ganan ventajas de descubribilidad.",
  },
  {
    id: 12,
    title: "Páginas de procedimientos sin schema",
    category: "llm",
    severity: "major",
    description: "Las páginas de procedimientos no tienen JSON-LD schema.",
    whyItMatters: "Tus páginas principales de procedimientos son invisibles para la IA a nivel de datos estructurados.",
  },
  {
    id: 13,
    title: "Imágenes de galería con alt text genérico",
    category: "accessibility",
    severity: "major",
    description: "Las imágenes de galería usan solo texto `alt` genérico de una palabra para cada imagen.",
    whyItMatters: "Los usuarios de lectores de pantalla escuchan palabras repetidas. Google Image Search tampoco puede indexar resultados para consultas específicas.",
  },
  {
    id: 14,
    title: "Imágenes placeholder en testimonios",
    category: "accessibility",
    severity: "major",
    description: "Las imágenes de testimonios usan el mismo placeholder en lugar de fotos reales.",
    whyItMatters: "Imágenes placeholder idénticas hacen que los testimonios parezcan fabricados en lugar de genuinos.",
  },
  {
    id: 15,
    title: "Error ortográfico en página Acerca de",
    category: "accessibility",
    severity: "major",
    description: "La página Acerca de contiene errores ortográficos visibles en secciones importantes.",
    whyItMatters: "Un error ortográfico visible en una página de credibilidad mina la atención al detalle que los pacientes esperan de una práctica médica.",
  },
  {
    id: 16,
    title: "Carga excesiva de scripts de terceros",
    category: "performance",
    severity: "major",
    description: "Más de 15 scripts de terceros compitiendo por recursos del navegador detectados.",
    whyItMatters: "Con 15+ scripts compitiendo, los tiempos de respuesta de interacción sufren. La mala interactividad afecta los rankings de Core Web Vitals de Google.",
  },
  {
    id: 17,
    title: "Script inline de rendimiento grande",
    category: "performance",
    severity: "major",
    description: "Se genera un bloque de script inline extremadamente grande en la parte superior de cada página.",
    whyItMatters: "Este script bloqueante retrasa el renderizado inicial. Los visitantes en conexiones móviles lentas ven una página en blanco.",
  },
  {
    id: 18,
    title: "Sin horarios de atención visibles",
    category: "content",
    severity: "major",
    description: "No se muestran horarios de atención en ningún lugar del sitio, solo teléfono y dirección.",
    whyItMatters: "Los pacientes potenciales no saben si alguien contestará llamadas y pueden asumir que el negocio está cerrado.",
  },
  {
    id: 19,
    title: "Sin email visible",
    category: "content",
    severity: "major",
    description: "No se encontró dirección de email visible en el sitio.",
    whyItMatters: "Los clientes que prefieren comunicación por email solo tienen un formulario de contacto, y algunos dudan en enviar información sensible por formularios anónimos.",
  },
  {
    id: 20,
    title: "Headers de seguridad faltantes",
    category: "technical",
    severity: "major",
    description: "No se detectaron headers de seguridad: sin Content-Security-Policy, X-Frame-Options, X-Content-Type-Options.",
    whyItMatters: "Los headers faltantes dejan el sitio vulnerable a cross-site scripting y clickjacking. Para un negocio que recopila información personal, esto es una preocupación de compliance.",
  },
  {
    id: 21,
    title: "Cuenta de autor SEO interna expuesta",
    category: "seo",
    severity: "major",
    description: "El sitemap de autores incluye una cuenta 'seo' como página de autor indexable.",
    whyItMatters: "Una página de autor 'seo' indexada señala que el contenido se escribe para motores de búsqueda en lugar de educación del paciente.",
  },

  // MINOR (25)
  {
    id: 22,
    title: "Títulos de páginas de procedimientos demasiado largos",
    category: "mobile",
    severity: "minor",
    description: "Varias páginas de procedimientos tienen títulos que exceden los límites de visualización móvil.",
    whyItMatters: "Cuando los pacientes buscan procedimientos en móvil, los títulos truncados se ven menos profesionales que los de competidores.",
  },
  {
    id: 23,
    title: "Imágenes SVG placeholder duplicadas",
    category: "mobile",
    severity: "minor",
    description: "Se usan imágenes SVG placeholder con fuentes de imagen reales en elementos `img` separados, resultando en tags duplicados.",
    whyItMatters: "Los enfoques de imagen duplicados pueden causar cambios de layout en conexiones móviles lentas.",
  },
  {
    id: 24,
    title: "Formato inconsistente de nombres de profesionales",
    category: "accessibility",
    severity: "minor",
    description: "Los nombres de profesionales usan formato inconsistente en diferentes páginas.",
    whyItMatters: "El formato inconsistente confunde a usuarios de lectores de pantalla y crea ambigüedad de entidad para buscadores.",
  },
  {
    id: 25,
    title: "Errores de capitalización en encabezados",
    category: "accessibility",
    severity: "minor",
    description: "Los encabezados de la página principal contienen errores de capitalización.",
    whyItMatters: "La capitalización inesperada puede causar que los lectores de pantalla pronuncien palabras de forma extraña.",
  },
  {
    id: 26,
    title: "Skip link con enfoque visual mínimo",
    category: "accessibility",
    severity: "minor",
    description: "Existe un enlace skip-to-content pero carece de contraste visual suficiente cuando se enfoca.",
    whyItMatters: "Los usuarios que solo usan teclado pueden no darse cuenta de que el skip link existe.",
  },
  {
    id: 27,
    title: "Jerarquía de encabezados inconsistente",
    category: "accessibility",
    severity: "minor",
    description: "Se usan tags `H5` para labels decorativos que aparecen visualmente encima de encabezados `H2`.",
    whyItMatters: "Los usuarios de lectores de pantalla dependen de la jerarquía de encabezados para entender la estructura de la página.",
  },
  {
    id: 28,
    title: "Títulos de páginas secundarias excesivamente largos",
    category: "seo",
    severity: "minor",
    description: "Múltiples páginas interiores tienen títulos que exceden los 100 caracteres.",
    whyItMatters: "Los títulos sobredimensionados se truncan en resultados de búsqueda.",
  },
  {
    id: 29,
    title: "Schema Organization débil",
    category: "llm",
    severity: "minor",
    description: "El schema `Organization` usa nombre del negocio pero excluye dirección, teléfono y especialización médica.",
    whyItMatters: "Sin dirección y teléfono, la IA no puede verificar la ubicación. Sin especialización médica, se trata como organización genérica.",
  },
  {
    id: 30,
    title: "Certificaciones profesionales no visibles como badges",
    category: "trust",
    severity: "minor",
    description: "Las certificaciones profesionales se mencionan solo en texto sin badges visuales.",
    whyItMatters: "Los logos de certificación visual se procesan en milisegundos versus texto que requiere lectura.",
  },
  {
    id: 31,
    title: "Organización inconsistente de categorías del blog",
    category: "content",
    severity: "minor",
    description: "El blog tiene múltiples categorías incluyendo artefactos internos y entradas con errores.",
    whyItMatters: "Las categorías mal organizadas impiden que los pacientes descubran contenido relacionado.",
  },
  {
    id: 32,
    title: "Roles de profesionales poco claros",
    category: "content",
    severity: "minor",
    description: "Múltiples profesionales listados sin diferenciar claramente roles y especialidades.",
    whyItMatters: "Los pacientes quieren saber quién realizará su procedimiento.",
  },
  {
    id: 33,
    title: "Información de copyright desactualizada",
    category: "content",
    severity: "minor",
    description: "El año de copyright no está claramente visible o actualizado.",
    whyItMatters: "Un año de copyright desactualizado señala que el sitio puede no estar activamente mantenido.",
  },
  {
    id: 34,
    title: "Foto de profesional de fuente no profesional",
    category: "trust",
    severity: "minor",
    description: "La foto del profesional usa un archivo que proviene de mensajería en lugar de fotografía profesional.",
    whyItMatters: "El nombre de archivo visible señala que la foto no proviene de fotografía profesional, minando expectativas de formalidad.",
  },
  {
    id: 35,
    title: "Estrategias de carga de imágenes inconsistentes",
    category: "performance",
    severity: "minor",
    description: "Múltiples enfoques de formato de imagen detectados: algunos usan `srcset`, otros usan tags `img` duales.",
    whyItMatters: "Las estrategias de carga inconsistentes causan cambio de layout acumulativo.",
  },
  {
    id: 36,
    title: "Carga excesiva de pesos de fuente",
    category: "performance",
    severity: "minor",
    description: "Se cargan 6 pesos de fuente diferentes más fuentes adicionales.",
    whyItMatters: "Cada peso de fuente es una solicitud separada que bloquea el renderizado de texto.",
  },
  {
    id: 37,
    title: "Ineficiencia de caché CDN",
    category: "performance",
    severity: "minor",
    description: "Los archivos minificados generan URLs con hash de versión que pueden no cachearse eficientemente.",
    whyItMatters: "Si los archivos minificados usan claves de caché inconsistentes, los visitantes recurrentes re-descargan assets.",
  },
  {
    id: 38,
    title: "Labels ARIA genéricos",
    category: "accessibility",
    severity: "minor",
    description: "No se detectaron landmarks ARIA visibles más allá de generación automática; los labels son genéricos.",
    whyItMatters: "Los landmarks ARIA bien implementados ayudan a usuarios de lectores de pantalla a saltar entre secciones principales.",
  },
  {
    id: 39,
    title: "Script de optimización interno expuesto",
    category: "technical",
    severity: "minor",
    description: "La optimización de lazy load genera un bloque de script inline grande parseado antes del contenido.",
    whyItMatters: "Un plugin de optimización de rendimiento que añade scripts bloqueantes grandes retrasa el renderizado inicial.",
  },
  {
    id: 40,
    title: "Servicios de analytics superpuestos",
    category: "technical",
    severity: "minor",
    description: "Múltiples analytics funcionan simultáneamente: Google Tag Manager, Clarity, Facebook Pixel, etc.",
    whyItMatters: "Los sistemas de tracking superpuestos disparan eventos duplicados, inflando datos de analytics.",
  },
  {
    id: 41,
    title: "Script de protección bot agresivo",
    category: "technical",
    severity: "minor",
    description: "Se detectó script de desafío de Cloudflare en algunas páginas, sugiriendo protección bot agresiva.",
    whyItMatters: "La protección bot excesivamente agresiva puede bloquear crawlers de buscadores y IA.",
  },
  {
    id: 42,
    title: "Schema markup en páginas de error",
    category: "technical",
    severity: "minor",
    description: "Las páginas 404 generan schema completo de `Organization` y `WebSite` a pesar de directiva `noindex`.",
    whyItMatters: "Generar schema completo en páginas de error desperdicia recursos del servidor.",
  },
  {
    id: 43,
    title: "Stack de plugins grande - riesgo de seguridad",
    category: "technical",
    severity: "minor",
    description: "WordPress con múltiples plugins activos aumentan la superficie de ataque.",
    whyItMatters: "Un stack grande de plugins incrementa vulnerabilidades de seguridad y problemas de compatibilidad.",
  },
  {
    id: 44,
    title: "Títulos de página de procedimiento principal demasiado largos",
    category: "mobile",
    severity: "minor",
    description: "Las páginas principales de procedimientos tienen títulos de más de 100 caracteres en móvil.",
    whyItMatters: "Los títulos largos se truncan en móvil, reduciendo el CTR frente a competidores optimizados.",
  },
  {
    id: 45,
    title: "Estructura de URL de procedimientos inconsistente",
    category: "seo",
    severity: "minor",
    description: "Los procedimientos se dividen entre custom post types y URLs basadas en páginas.",
    whyItMatters: "Dos estructuras de URL diferentes confunden a los buscadores sobre la arquitectura del sitio.",
  },
  {
    id: 46,
    title: "Sin métricas de prueba social visibles",
    category: "trust",
    severity: "minor",
    description: "Los enlaces de redes sociales están presentes pero sin contadores de seguidores ni feeds embebidos.",
    whyItMatters: "La prueba social visible refuerza la credibilidad. Sin feeds embebidos, los visitantes deben salir del sitio.",
  },

  // OPPORTUNITIES (12)
  {
    id: 47,
    title: "Sin página de servicios centralizada",
    category: "content",
    severity: "opportunity",
    description: "No existe una página dedicada de servicios o procedimientos; los procedimientos están dispersos en múltiples estructuras de URL.",
    whyItMatters: "Los pacientes que buscan todos los procedimientos disponibles no tienen una sola página para visitar.",
  },
  {
    id: 48,
    title: "Sin sección de información de seguros/financiación",
    category: "content",
    severity: "opportunity",
    description: "No se detectó página de información de seguros o financiación.",
    whyItMatters: "La cobertura de seguros es un factor importante de decisión. Los pacientes que buscan cobertura no encontrarán tu práctica.",
  },
  {
    id: 49,
    title: "Guías post-tratamiento sin enlazar",
    category: "content",
    severity: "opportunity",
    description: "Existen guías post-tratamiento pero no están enlazadas prominentemente desde las páginas de procedimientos correspondientes.",
    whyItMatters: "Las guías post-tratamiento demuestran cuidado más allá del procedimiento. Si los pacientes no pueden encontrarlas fácilmente, estos recursos valiosos se desperdician.",
  },
  {
    id: 50,
    title: "Sin schema MedicalProcedure",
    category: "llm",
    severity: "opportunity",
    description: "No se encontró schema `MedicalProcedure` en ninguna de las páginas principales de procedimientos.",
    whyItMatters: "El schema `MedicalProcedure` permite a la IA entender y citar tus ofertas específicas, tiempos de recuperación y enfoque.",
  },
  {
    id: 51,
    title: "Sin botón CTA sticky en móvil",
    category: "mobile",
    severity: "opportunity",
    description: "No se detectó CTA sticky móvil o botón click-to-call; el teléfono solo aparece en el header.",
    whyItMatters: "Los pacientes que investigan en móvil a menudo quieren llamar inmediatamente. Sin botones sticky, deben hacer scroll arriba.",
  },
  {
    id: 52,
    title: "Widget de traducción superpuesto en móvil",
    category: "mobile",
    severity: "opportunity",
    description: "El botón flotante de traducción puede superponerse a contenido o CTAs en viewports móviles estrechos.",
    whyItMatters: "Un widget flotante cubriendo botones de reserva en pantallas pequeñas podría impedir conversiones.",
  },
  {
    id: 53,
    title: "Plugin de chat en vivo inactivo",
    category: "technical",
    severity: "opportunity",
    description: "Se carga JavaScript de chat en vivo en cada página, pero no se observó widget de chat visible.",
    whyItMatters: "Si el widget de chat carga JavaScript pero no está activo, añade peso a la página sin valor.",
  },
  {
    id: 54,
    title: "Múltiples sistemas de formularios",
    category: "technical",
    severity: "opportunity",
    description: "Se detectaron scripts de formularios de múltiples fuentes.",
    whyItMatters: "Múltiples sistemas de formularios aumentan las posibilidades de fallos y recopilación de datos inconsistente.",
  },
  {
    id: 55,
    title: "Técnica innovadora de profesional no destacada",
    category: "trust",
    severity: "opportunity",
    description: "Un profesional tiene técnicas innovadoras propias pero el logro está enterrado en la biografía.",
    whyItMatters: "Tener un profesional que inventó una técnica nombrada es extraordinario y debería destacarse prominentemente.",
  },
  {
    id: 56,
    title: "Sin aviso de compliance/privacidad visible",
    category: "trust",
    severity: "opportunity",
    description: "No se detectó aviso de compliance de datos o referencia a política de privacidad claramente visible.",
    whyItMatters: "Los pacientes que envían información de salud esperan garantías de privacidad. Sin avisos visibles de compliance, los pacientes dudan.",
  },
  {
    id: 57,
    title: "Credenciales del profesional principal no destacadas",
    category: "trust",
    severity: "opportunity",
    description: "Las credenciales fuertes del profesional principal están confinadas solo a su página de perfil.",
    whyItMatters: "Estas potentes señales de confianza solo aparecen en la página de perfil. Los pacientes que llegan a otras páginas nunca las ven.",
  },
  {
    id: 58,
    title: "Página de reviews sin puntuación agregada",
    category: "trust",
    severity: "opportunity",
    description: "La página de reseñas existe pero no muestra rápidamente una puntuación agregada.",
    whyItMatters: "Los pacientes no pueden escanear rápidamente la credibilidad. Los competidores con ratings agregados prominentes establecen confianza inmediatamente.",
  },
];

export const DEMO_AUDIT: AuditReport = {
  id: "demo-001",
  slug: "clinica-estetica-bella",
  token: "demo-token-123",
  businessName: "Clínica Estética Bella",
  contactName: "Dra. María García",
  siteUrl: "https://clinicaesteticabella.com",
  auditDate: "17 de Marzo, 2026",
  overallScore: 50,
  overallGrade: "D",
  totalIssues: 58,
  criticalCount: 3,
  majorCount: 18,
  minorCount: 25,
  oppsCount: 12,
  categories: [
    { key: "mobile", label: "Mobile y Responsividad", score: 65, issueCount: 5, status: "Puede mejorar", icon: "📱" },
    { key: "seo", label: "SEO y Visibilidad en Búsquedas", score: 52, issueCount: 9, status: "Necesita atención", icon: "🔍" },
    { key: "llm", label: "LLM y Preparación para IA", score: 28, issueCount: 8, status: "Crítico", icon: "🤖" },
    { key: "accessibility", label: "Accesibilidad (WCAG 2.1 AA)", score: 48, issueCount: 8, status: "Necesita atención", icon: "♿" },
    { key: "performance", label: "Rendimiento", score: 55, issueCount: 5, status: "Necesita atención", icon: "⚡" },
    { key: "content", label: "Contenido y Arquitectura", score: 55, issueCount: 8, status: "Necesita atención", icon: "📄" },
    { key: "trust", label: "Confianza y Credibilidad", score: 50, issueCount: 8, status: "Necesita atención", icon: "🛡️" },
    { key: "technical", label: "Implementación Técnica", score: 50, issueCount: 7, status: "Necesita atención", icon: "⚙️" },
  ],
  issues: demoIssues,
  vitals: {
    lcp: 18.1,
    cls: 0.0,
    inp: 350,
    fcp: 5.8,
    tbt: 450,
    si: 8.2,
  },
  summary:
    "Se han identificado 58 problemas en 8 categorías que afectan significativamente la visibilidad digital de Clínica Estética Bella. Las áreas más críticas incluyen la preparación para IA (28/100), donde el sitio carece de datos estructurados esenciales para ser descubierto por asistentes de IA como ChatGPT y Gemini. La accesibilidad (48/100) y la confianza/credibilidad (50/100) también requieren atención urgente. El sitio tiene una base de contenido sólida pero necesita optimización técnica significativa para competir efectivamente en el panorama digital actual.",
};
